steps:
  # データベースマイグレーションを実行
  - name: 'node:18'
    entrypoint: yarn
    args: ['prisma', 'migrate', 'deploy']
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'

  # 1. Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/nestjs-cloud-run'
      - '.'

  # 2. ビルドしたイメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/nestjs-cloud-run'

  # 3. Cloud Run にデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - nestjs-cloud-run
      # 上でプッシュしたイメージを指定
      - '--image'
      - 'gcr.io/$PROJECT_ID/nestjs-cloud-run'
      # マネージドプラットフォームでデプロイ
      - '--platform'
      - managed
      # リージョン（必要に応じて変更）
      - '--region'
      - us-central1
      # 非認証アクセスを許可する場合
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/nestjs-cloud-run'
